CREATE TABLE T_USER_ACCOUNT (
  USER_ID VARCHAR(50) NOT NULL UNIQUE,
  PWD_HASH VARCHAR(255) NOT NULL,
  USER_TYPE VARCHAR(50) NOT NULL,
  LAST_ONLINE DATETIME NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  AGE INT NOT NULL,
  CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE T_RESTAURANT_USER_PROFILE (
  RESTAURANT_USER_PROFILE_ID INT NOT NULL AUTO_INCREMENT,
  RESTAURANT_NAME VARCHAR(50) NOT NULL,
  RESTAURANT_OWNER_NAME VARCHAR(50) NOT NULL,
  FOOD_OPTIONS_TAG VARCHAR(10),
  BIOGRAPHY VARCHAR(150),
  BOOKING_URL VARCHAR(50),
  CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESTAURANT_USER_PROFILE_ID)
);

CREATE TABLE T_IMAGE (
  IMAGE_ID INT NOT NULL AUTO_INCREMENT,
  PROFILE_ID VARCHAR(50) NOT NULL,
  RESTAURANT_USER_PROFILE_ID INT NOT NULL,
  DESCRIPTION VARCHAR(255),
  IMAGE VARBINARY(64000) NOT NULL,
  CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (IMAGE_ID),
  FOREIGN KEY (PROFILE_ID) REFERENCES T_USER_ACCOUNT (USER_ID),
  FOREIGN KEY (RESTAURANT_USER_PROFILE_ID) REFERENCES T_RESTAURANT_USER_PROFILE (RESTAURANT_USER_PROFILE_ID)
);

CREATE TABLE T_DINER_USER_PROFILE (
  DINER_USER_PROFILE_ID INT NOT NULL AUTO_INCREMENT,
  USER_ID VARCHAR(50) NOT NULL,
  FOOD_PREFERENCES_TAG VARCHAR(10),
  BIOGRAPHY VARCHAR(150),
  CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (DINER_USER_PROFILE_ID),
  FOREIGN KEY (USER_ID) REFERENCES T_USER_ACCOUNT (USER_ID)
);

CREATE TABLE T_MESSAGE (
	MSG_ID INT NOT NULL AUTO_INCREMENT,
    SENDER_ID VARCHAR(50) NOT NULL,
    RECEIVER_ID VARCHAR(50) NOT NULL,
	MESSAGE VARCHAR(1000) NOT NULL,
    CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MSG_ID),
	FOREIGN KEY (SENDER_ID) REFERENCES T_USER_ACCOUNT (USER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES T_USER_ACCOUNT (USER_ID)
);

CREATE table T_BOOKING_DETAILS (
	BOOKING_DETAILS_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    RESTAURANT_USER_PROFILE_ID INT NOT NULL,
    NO_OF_PAX INT NOT NULL,
    CONTACT_NO VARCHAR(15) NOT NULL,
    DINING_DATE_TIME DATETIME NOT NULL,
    CRT_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOKING_DETAILS_ID),
	FOREIGN KEY (USER_ID) REFERENCES T_USER_ACCOUNT (USER_ID),
    FOREIGN KEY (RESTAURANT_USER_PROFILE_ID) REFERENCES T_RESTAURANT_USER_PROFILE (RESTAURANT_USER_PROFILE_ID)
);

ALTER TABLE T_USER_ACCOUNT RENAME TO T_USER;
