name: Backend 2

# Controls when the workflow will run
# Workflow runs when changes are pushed
on:
  push:
    branches: [ "init" ]

jobs:
  backend2:
    runs-on: [self-hosted, Windows,dev]

    steps:
      - uses: actions/checkout@v3
      - name: Stop Backend2
        run: nssm stop  Restaurant2
      - name: Run JUnit Tests
        run: |
          cd ./backend 1/src
          mvn test
      - name: Deploy
        run: mvn package
        shell: cmd
        working-directory: ./backend 1
      - name: Move Item
        run: Copy-Item -Path "C:\Users\Administrator\Desktop\actions-runner\_work\food-adventures\food-adventures\backend 1\target\foodAdventuresBackend1-0.0.1-SNAPSHOT.jar" -Destination "C:\inetpub\Sites\BackEnd\Backend2.jar" -Recurse -force
      - name: Start Backend2
        run: nssm start  Restaurant2
