# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:


 
  backend:
    runs-on: [self-hosted, Windows,dev]

    steps:
      - uses: actions/checkout@v3
      - name: Stop Backend1
        run: nssm stop  RestaurantService
      - name: Deploy
        run: mvn package
        shell: cmd
        working-directory: ./backend
      - name: Start Backend1
        run: nssm start  RestaurantService

 