# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: [self-hosted, Windows,dev]

    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: mvnw.cmd deploy
        shell: cmd
        working-directory: ./backend

 
